#!/bin/bash

ENV=""

#
# Color Codes
#
red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
end=$'\e[0m'

bold=$'\e[1m'
italic=$'\e[3m'
underline=$'\e[4m'

function usage {
	echo
    echo Usage : $0 'options [ -h host ]';
    echo '  options can be a sequence of the following:';
	echo '      --env  (mandatory)      : can be mac, ubuntu, debian';
    echo '      --help                  : print this usage';
    exit 1;
}

while [ $# -gt 0 ];
do
    [ "$1" == '--env' ] && { ENV=$2; shift; }
    [ "$1" == '--help' ] && { usage; }

    shift;
done

#
# Check mandatories
#
[ "$ENV" == "" ] && usage;

#
# Check if already installed
#
if [ "$(which git)" ]; then
    echo "${grn}git already installed ${end}"
    echo
    echo "${bold}Version Information${end}:=> $(git --version)"
    exit 1;
fi

case $ENV in
	ubuntu)
		sudo apt-get install git
		;;
	debian)
		sudo apt-get install git
		;;
	mac)
		brew install git
		;;
	*)
		echo "${red}Error:${end} Invalid env parameter provided"
		usage
		exit 1
		;;
esac
