#! /bin/bash

#
# Begin nvm installation
#
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source ~/.nvm/nvm.sh

nvm install 11.4.0
nvm use 11.4.0

#
# pm2 install
#
npm install -g pm2

#
# bunyan install
#
npm install -g bunyan
